[editor]
bufferline = "always"
auto-pairs = false

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[keys.normal]
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E tig blame TODO"
