[[language]]
name = "go"
formatter = { command = "goimports" }

# [[language]]
# name = "rst"
# language-servers = [{ name = "ltex-ls"}]

# [language-server.ltex-ls.config]
# ltex.disabledRules = { "en-US" = ["PROFANITY"], "en-GB" = ["PROFANITY"] }
# ltex.dictionary = { "en-US" = ["builtin"], "en-GB" = ["builtin"] }

# [language-server.ltex-ls]
# command = "/opt/ltex-ls/ltex-ls-plus-18.4.0/bin/ltex-ls-plus"


[[language]]
name = "rst"
language-servers = [ { name = "vale-ls" } ]
